version: '3.0'

services:
  frontend:
    image: node:16
    container_name: group-gpt-frontend
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - intern
    command: "npm run dev -- --host"
  api:
    container_name: group-gpt-api
    build:
      dockerfile: ./Dockerfile.api
    volumes:
      - ./api:/code/app
    networks:
      - intern
  openai:
    container_name: group-gpt-openai
    image: openai
    env_file:
      - openai.env
    build:
      dockerfile: ./Dockerfile.openai
    volumes:
      - ./app:/code/app
    networks:
      - intern
  mongo:
    container_name: group-gpt-mongo
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    networks:
      - intern
    env_file: 
      - ./mongo.env

  mongo-express:
    container_name: group-gpt-mongo-express
    image: mongo-express
    restart: always
    networks:
      - intern
    ports:
      - 8081:8081
    env_file: 
      - ./mongo.env
  proxy:
    container_name: group-gpt-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/cert/nginx
    networks:
      - intern
    ports:
      - 80:80
      - 443:443

networks:
  intern:
