version: '3.0'

services:
  frontend:
    image: node:16
    container_name: group-gpt-frontend
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - intern
    command: "npm run dev -- --host"
  backend:
    container_name: group-gpt-backend
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/code/app
    networks:
      - intern
  proxy:
    container_name: group-gpt-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/cert/nginx
    networks:
      - intern
    ports:
      - 80:80
      - 443:443

networks:
  intern:
